### ISSUE TITLE
Determinar Papéis da Equipe

### ISSUE THREAD

**Issue by rcopstein** [rcopstein/silver-garbanzo#1]
Determinar o papel de cada membro da equipe usando o método XP

**Comment by rcopstein** [comment]
- XP Coach
- XP Customer
- XP Programmer
- XP Programmer (Administrator)
- XP Tracker
- XP Tester

**Comment by IanCaraLegal** [comment]
XP Coach - Ian
XP Tracker - Ian

**Comment by arielril** [comment]
XP Programmer
XP Tester

**Comment by rcopstein** [comment]
XP Coach - @IanCaraLegal 
XP Customer - @rcopstein
XP Programmer - @arielril 
XP Programmer (Administrator) - @rcopstein
XP Tracker - @IanCaraLegal 
XP Tester - @arielril
